#!/usr/bin/env fish

# This Tab Completion script was generated by the Cova Library.
# Details at https://github.com/00JCIV00/cova


# Fish Completion Installation Instructions for covademo
# 1. Place this script in ~/.config/fish/completions/covademo-completion.fish
#
# 2. Fish will automatically load it on next shell start.
#
# 3. Or source it manually:
#    source /path/to/covademo-completion.fish


complete -c covademo -f -n '__fish_use_subcommand' -a sub-cmd -d 'A demo sub command.'
complete -c covademo -f -n '__fish_use_subcommand' -a basic -d 'The most basic Command.'
complete -c covademo -f -n '__fish_use_subcommand' -a nest-1 -d 'Nested Level 1.'
complete -c covademo -f -n '__fish_use_subcommand' -a struct-cmd -d 'A demo sub command made from a struct.'
complete -c covademo -f -n '__fish_use_subcommand' -a union-cmd -d 'A demo sub command made from a union.'
complete -c covademo -f -n '__fish_use_subcommand' -a fn-cmd -d 'A demo sub command made from a function.'
complete -c covademo -f -n '__fish_use_subcommand' -a add-user -d 'A demo sub command for adding a user.'
complete -c covademo -f -n '__fish_use_subcommand' -a help -d 'Show help'
complete -c covademo -f -n '__fish_use_subcommand' -a usage -d 'Show usage'
complete -c covademo -n '__fish_use_subcommand' -s s -l string -d 'A string option. (Can be given up to 4 times.)'
complete -c covademo -n '__fish_use_subcommand' -s i -l int -d 'An integer option. (Can be given up to 10 times.)'
complete -c covademo -n '__fish_use_subcommand' -s f -l float -d 'An float option. (Can be given up to 10 times.)'
complete -c covademo -n '__fish_use_subcommand' -s F -l file -d 'A filepath option.'
complete -c covademo -n '__fish_use_subcommand' -s o -l ordinal -d 'An ordinal number option.'
complete -c covademo -n '__fish_use_subcommand' -s c -l cardinal -d 'A cardinal number option.'
complete -c covademo -n '__fish_use_subcommand' -s t -l toggle -d 'A toggle/boolean option.'
complete -c covademo -n '__fish_use_subcommand' -s b -l bool -d 'A toggle/boolean option.'
complete -c covademo -n '__fish_use_subcommand' -s v -l verbosity -d 'Set the CovaDemo verbosity level. (WIP)'
complete -c covademo -n '__fish_use_subcommand' -l help
complete -c covademo -n '__fish_use_subcommand' -l usage
complete -c covademo -f -n '__fish_seen_subcommand_from sub-cmd' -a help -d 'Show help'
complete -c covademo -f -n '__fish_seen_subcommand_from sub-cmd' -a usage -d 'Show usage'
complete -c covademo -n '__fish_seen_subcommand_from sub-cmd' -s i -d 'A nested integer option.'
complete -c covademo -n '__fish_seen_subcommand_from sub-cmd' -s s -l nested_str -d 'A nested string option.'
complete -c covademo -n '__fish_seen_subcommand_from sub-cmd' -l help
complete -c covademo -n '__fish_seen_subcommand_from sub-cmd' -l usage
complete -c covademo -f -n '__fish_seen_subcommand_from basic' -a help -d 'Show help'
complete -c covademo -f -n '__fish_seen_subcommand_from basic' -a usage -d 'Show usage'
complete -c covademo -n '__fish_seen_subcommand_from basic' -l help
complete -c covademo -n '__fish_seen_subcommand_from basic' -l usage
complete -c covademo -f -n '__fish_seen_subcommand_from nest-1' -a nest-2 -d 'Nested Level 2.'
complete -c covademo -f -n '__fish_seen_subcommand_from nest-1' -a help -d 'Show help'
complete -c covademo -f -n '__fish_seen_subcommand_from nest-1' -a usage -d 'Show usage'
complete -c covademo -n '__fish_seen_subcommand_from nest-1' -l help
complete -c covademo -n '__fish_seen_subcommand_from nest-1' -l usage
complete -c covademo -f -n '__fish_seen_subcommand_from nest-2' -a nest-3 -d 'Nested Level 3.'
complete -c covademo -f -n '__fish_seen_subcommand_from nest-2' -a help -d 'Show help'
complete -c covademo -f -n '__fish_seen_subcommand_from nest-2' -a usage -d 'Show usage'
complete -c covademo -n '__fish_seen_subcommand_from nest-2' -l help
complete -c covademo -n '__fish_seen_subcommand_from nest-2' -l usage
complete -c covademo -f -n '__fish_seen_subcommand_from nest-3' -a nest-4 -d 'Nested Level 4.'
complete -c covademo -f -n '__fish_seen_subcommand_from nest-3' -a help -d 'Show help'
complete -c covademo -f -n '__fish_seen_subcommand_from nest-3' -a usage -d 'Show usage'
complete -c covademo -n '__fish_seen_subcommand_from nest-3' -s n -l non-inheritable -d 'Non-Inheritable Option'
complete -c covademo -n '__fish_seen_subcommand_from nest-3' -s i -l inheritable -d 'Inheritable Option'
complete -c covademo -n '__fish_seen_subcommand_from nest-3' -l help
complete -c covademo -n '__fish_seen_subcommand_from nest-3' -l usage
complete -c covademo -f -n '__fish_seen_subcommand_from nest-4' -a help -d 'Show help'
complete -c covademo -f -n '__fish_seen_subcommand_from nest-4' -a usage -d 'Show usage'
complete -c covademo -n '__fish_seen_subcommand_from nest-4' -l help
complete -c covademo -n '__fish_seen_subcommand_from nest-4' -l usage
complete -c covademo -f -n '__fish_seen_subcommand_from struct-cmd' -a inner-cmd -d 'An inner/nested command for struct-cmd'
complete -c covademo -f -n '__fish_seen_subcommand_from struct-cmd' -a help -d 'Show help'
complete -c covademo -f -n '__fish_seen_subcommand_from struct-cmd' -a usage -d 'Show usage'
complete -c covademo -n '__fish_seen_subcommand_from struct-cmd' -s i -l int -d 'The first Integer Value for the struct-cmd.'
complete -c covademo -n '__fish_seen_subcommand_from struct-cmd' -s s -l str -d 'The \'str\' Option.'
complete -c covademo -n '__fish_seen_subcommand_from struct-cmd' -s S -l str2 -d 'The \'str2\' Option.'
complete -c covademo -n '__fish_seen_subcommand_from struct-cmd' -s f -l flt -d 'The \'flt\' Option.'
complete -c covademo -n '__fish_seen_subcommand_from struct-cmd' -s I -l int2 -d 'The \'int2\' Option.'
complete -c covademo -n '__fish_seen_subcommand_from struct-cmd' -s m -l multi-int -d 'The \'multi-int\' Value.'
complete -c covademo -n '__fish_seen_subcommand_from struct-cmd' -s M -l multi-str -d 'The \'multi-str\' Value.'
complete -c covademo -n '__fish_seen_subcommand_from struct-cmd' -s r -l rgb-enum -d 'The \'rgb-enum\' Option.'
complete -c covademo -n '__fish_seen_subcommand_from struct-cmd' -s t -l struct-bool -d 'The \'struct_bool\' Option of type \'toggle\'.'
complete -c covademo -n '__fish_seen_subcommand_from struct-cmd' -s T -l struct-str -d 'The \'struct_str\' Option of type \'text\'.'
complete -c covademo -n '__fish_seen_subcommand_from struct-cmd' -s R -l struct-int -d 'The \'struct_int\' Option of type \'i64\'.'
complete -c covademo -n '__fish_seen_subcommand_from struct-cmd' -l help
complete -c covademo -n '__fish_seen_subcommand_from struct-cmd' -l usage
complete -c covademo -f -n '__fish_seen_subcommand_from inner-cmd' -a help -d 'Show help'
complete -c covademo -f -n '__fish_seen_subcommand_from inner-cmd' -a usage -d 'Show usage'
complete -c covademo -n '__fish_seen_subcommand_from inner-cmd' -s i -l in-bool -d 'The \'in_bool\' Option of type \'toggle\'.'
complete -c covademo -n '__fish_seen_subcommand_from inner-cmd' -s I -l in-float -d 'The \'in_float\' Option of type \'f32\'.'
complete -c covademo -n '__fish_seen_subcommand_from inner-cmd' -s H -l h-string -d 'The \'h_string\' Option of type \'text\'.'
complete -c covademo -n '__fish_seen_subcommand_from inner-cmd' -l help
complete -c covademo -n '__fish_seen_subcommand_from inner-cmd' -l usage
complete -c covademo -f -n '__fish_seen_subcommand_from union-cmd' -a help -d 'Show help'
complete -c covademo -f -n '__fish_seen_subcommand_from union-cmd' -a usage -d 'Show usage'
complete -c covademo -n '__fish_seen_subcommand_from union-cmd' -s i -l int -d 'The first Integer Value for the union-cmd.'
complete -c covademo -n '__fish_seen_subcommand_from union-cmd' -s s -l str -d 'The first String Value for the union-cmd.'
complete -c covademo -n '__fish_seen_subcommand_from union-cmd' -l help
complete -c covademo -n '__fish_seen_subcommand_from union-cmd' -l usage
complete -c covademo -f -n '__fish_seen_subcommand_from fn-cmd' -a help -d 'Show help'
complete -c covademo -f -n '__fish_seen_subcommand_from fn-cmd' -a usage -d 'Show usage'
complete -c covademo -n '__fish_seen_subcommand_from fn-cmd' -l help
complete -c covademo -n '__fish_seen_subcommand_from fn-cmd' -l usage
complete -c covademo -f -n '__fish_seen_subcommand_from add-user' -a help -d 'Show help'
complete -c covademo -f -n '__fish_seen_subcommand_from add-user' -a usage -d 'Show usage'
complete -c covademo -n '__fish_seen_subcommand_from add-user' -s f -l fname -d 'The \'fname\' Option.'
complete -c covademo -n '__fish_seen_subcommand_from add-user' -s l -l lname -d 'The \'lname\' Option.'
complete -c covademo -n '__fish_seen_subcommand_from add-user' -s a -l age -d 'The \'age\' Option.'
complete -c covademo -n '__fish_seen_subcommand_from add-user' -s A -l admin -d 'The \'admin\' Option.'
complete -c covademo -n '__fish_seen_subcommand_from add-user' -s r -l ref-ids -d 'The \'ref-ids\' Value.'
complete -c covademo -n '__fish_seen_subcommand_from add-user' -l help
complete -c covademo -n '__fish_seen_subcommand_from add-user' -l usage
